import "./globals.css";

import type { Metadata } from "next";

import Header from "./components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body>
        <div className="flex min-h-screen flex-col items-center justify-center">
          <Header />
          <main className="flex flex-1 w-full max-w-5xl flex-col items-center justify-between py-10 px-5 md:py-32 md:px-16 sm:items-start">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
