import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body>
        <div className="flex min-h-screen items-center justify-center">
          <main className="flex min-h-screen w-full max-w-3xl flex-col items-center justify-between py-10 px-5 md:py-32 md:px-16 sm:items-start">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
